# Generated by Django 5.2.1 on 2025-05-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('desc', models.TextField(max_length=400)),
                ('category', models.CharField(choices=[('HP', 'Highted Pot'), ('SM', 'Small Pot'), ('FP', 'Fat Pot')], max_length=2)),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
